### ISSUE TITLE
M997 with no S parameter caused an ArgumentNullException

### ISSUE THREAD

**Issue by dc42** [Duet3D/DuetSoftwareFramework#147]
Running DSF 3.1.1. if I send M997 then the command fails with message:

Error: operation failed (reason: ArgumentNullException in SimpleCode: Value cannot be null. (Parameter: 'input')).

**Comment by chrishamm** [comment]
I am closing this because I've been unable to reproduce this. If it happens again, please share the stack trace from the DCS log.
