### ISSUE TITLE
make debs fails on unexpanded list

### ISSUE THREAD

**Issue by M-Pixel** [Duet3D/DuetSoftwareFramework#163]
1. Check-out in Debian Buster
2. Install `dotnet-sdk-3.1`, `libxml2-utils`, `make`, and `rsync`
3. `make debs`

`sed: can't read /.../bin/packages/deb/duetcontrolserver_3.2.0_armhf/DEBIAN/{control,changelog}: No such file or directory`

Is there a Make plugin or configuration that's supposed to be expanding the curly-braced lists?

**Comment by gtjoseph** [comment]
Is bash your shell?  If not, I can probably make those discrete commands.

**Comment by M-Pixel** [comment]
> I can probably make those discrete commands.

I've already done so on my end, can send over a PR.

Bash is indeed my shell.  I'm working off of the `3.2.0` tag.

**Comment by chrishamm** [comment]
Please feel free to send over a PR for this, I don't use the Makefiles. You may have better luck with the build script in the pkg directory.

**Comment by gtjoseph** [comment]
Odd.  Anyway, I'll fix it up.  I've got another fix for the Makefile to push up anyay.

**Comment by gtjoseph** [comment]
Pull request submitted.
