### ISSUE TITLE
Upgrade expansion board firmware along with mainboard firmware.

### ISSUE THREAD

**Issue by T3P3** [Duet3D/DuetSoftwareFramework#167]
when apt is used to upgrade DSF,DWC and RRF on an SBC connected Duet it currently upgrades RRF mainboard firmware but not CAN connected expansion boards (although the firmware files are installed so the user can manually upgrade them).

It would be more consistent to allow these to be upgraded at the same time (and this is generally the recommended behaviour for RRF to keep all versions in line). 

This relates to a second requirement to prompt the user before upgrading any firmware as part of the upgrade process, until they have confirmed they have read the release notes.

**Comment by chrishamm** [comment]
Tested and working. Release notes are still TBC
