### ISSUE TITLE
[Bug]: stats fails to get file info on recent kernels

### ISSUE THREAD

**Issue by LoicGRENON** [Duet3D/DuetSoftwareFramework#183]
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/29575/dwc-plugin-uninstallation-issue-on-armbian-sbc

### Which Duet products are you using?

- [X] None

### Firmware Version

3.4.5

### Duet Web Control Version

DWC 3.4.5

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [X] Yes I use a SBC.
- [ ] No I do not use a SBC.

### What happened?

I'm using DSF/DWC 3.4.5 on a SBC running an Armbian image with linux kernel 5.15.48-sunxi64

When I try to uninstall a plugin, I get `ArgumentException in UninstallPlugin: Failed to get file info (error 22)`.
After investigating, it seems `stat` fails to get file info on the plugin manifest file.
This issue has been introduced by [this commit](https://github.com/Duet3D/DuetSoftwareFramework/commit/7739e916c8fb6595d4ae73fc5d1bac131edf5df6#diff-b494305c06eb76f8c94cc28110419e5b82dc18da06e884f0cee4a36b04f4ebf0) when checking the permissions on the manifest file.

This issue is not present on the DuetPi image running linux kernel 5.10.103 (32 bits).

After some more investigation, I found [that post on StackOverFlow](https://stackoverflow.com/questions/69777374/how-to-get-linux-file-permissions-in-net-5-net-6-without-mono-posix-with-p-i) which explains what's going on.
The stat function [actually uses](https://github.com/Duet3D/DuetSoftwareFramework/blob/master/src/LinuxApi/Interop/Libc/Interop.stat.cs#L25) the `__xstat` function of libc which cause the problem on more recent kernels probably because STATVER is set to an incorrect version for these kernels

**Comment by chrishamm** [comment]
Fix merged, thanks again!
