### ISSUE TITLE
[FeatureRequest]: Buzzer through SBC Sound System

### ISSUE THREAD

**Issue by gdwinslow** [Duet3D/DuetSoftwareFramework#199]
### Is your feature request related to a problem? Please describe.

Just of interest.  I don't have Screen on my Raspberry PI, or panel duo

### Describe the solution you propose.

Ex. It would be great if...
The buzzer signal was Piped through the SBC {Raspberry PI} sound system.  This would also work if HDMI monitor were attached to the SBC or VNC is setup for remote sound as well. On Raspberry PI SBC: Raspberry PI 3,4 and 5 at lest

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by T3P3** [comment]
This could be done by capturing M300 and either diverting it to the SBC sound system or forking it and sending it to the sound system as well as letting it continue on to RRF. In either case it should be handled by the SBC as a UI feature so moving it to DSF for further discussion.

**Comment by T3P3** [comment]
this could be done through a DSF plugin.
