### ISSUE TITLE
[FeatureRequest]:  a more redundant data type in DSF for g-codes with MinorNumber

### ISSUE THREAD

**Issue by fragrama17** [Duet3D/DuetSoftwareFramework#209]
### Is your feature request related to a problem? Please describe.

https://forum.duet3d.com/topic/36876/sbyte-int8_t-type-in-dsf-for-g-codes-with-minornumber

### Describe the solution you propose.

a more redundant data type like ushort or uint

**Comment by chrishamm** [comment]
Now changed, see forum reply and referenced comment.
